{-# LANGUAGE OverloadedStrings #-}
module Element where

import Selector

-- List from http://www.w3.org/TR/html-markup/elements.html

a, abbr, address, area, article, aside, audio, b, base, bdi, bdo, blockquote,
  body, br, button, canvas, caption, cite, code, col, colgroup, command,
  datalist, dd, del, details, dfn, div, dl, dt, em, embed, fieldset,
  figcaption, figure, footer, form, h1, h2, h3, h4, h5, h6, head, header,
  hgroup, hr, html, i, iframe, img, input, ins, kbd, keygen, label, legend, li,
  link, map, mark, menu, meta, meter, nav, noscript, object, ol, optgroup,
  option, output, p, param, pre, progress, q, rp, rt, ruby, s, samp, script,
  section, select, small, source, span, strong, style, sub, summary, sup,
  table, tbody, td, textarea, tfoot, th, thead, time, title, tr, track, u, ul,
  var, video, wbr :: Selector

a = "a"
abbr = "abbr"
address = "address"
area = "area"
article = "article"
aside = "aside"
audio = "audio"
b = "b"
base = "base"
bdi = "bdi"
bdo = "bdo"
blockquote = "blockquote"
body = "body"
br = "br"
button = "button"
canvas = "canvas"
caption = "caption"
cite = "cite"
code = "code"
col = "col"
colgroup = "colgroup"
command = "command"
datalist = "datalist"
dd = "dd"
del = "del"
details = "details"
dfn = "dfn"
div = "div"
dl = "dl"
dt = "dt"
em = "em"
embed = "embed"
fieldset = "fieldset"
figcaption = "figcaption"
figure = "figure"
footer = "footer"
form = "form"
h1 = "h1"
h2 = "h2"
h3 = "h3"
h4 = "h4"
h5 = "h5"
h6 = "h6"
head = "head"
header = "header"
hgroup = "hgroup"
hr = "hr"
html = "html"
i = "i"
iframe = "iframe"
img = "img"
input = "input"
ins = "ins"
kbd = "kbd"
keygen = "keygen"
label = "label"
legend = "legend"
li = "li"
link = "link"
map = "map"
mark = "mark"
menu = "menu"
meta = "meta"
meter = "meter"
nav = "nav"
noscript = "noscript"
object = "object"
ol = "ol"
optgroup = "optgroup"
option = "option"
output = "output"
p = "p"
param = "param"
pre = "pre"
progress = "progress"
q = "q"
rp = "rp"
rt = "rt"
ruby = "ruby"
s = "s"
samp = "samp"
script = "script"
section = "section"
select = "select"
small = "small"
source = "source"
span = "span"
strong = "strong"
style = "style"
sub = "sub"
summary = "summary"
sup = "sup"
table = "table"
tbody = "tbody"
td = "td"
textarea = "textarea"
tfoot = "tfoot"
th = "th"
thead = "thead"
time = "time"
title = "title"
tr = "tr"
track = "track"
u = "u"
ul = "ul"
var = "var"
video = "video"
wbr = "wbr"

