{-# LANGUAGE OverloadedStrings #-}
module Html where

import Data.String

import Selector

-- From: http://www.whatwg.org/specs/web-apps/current-work/multipage/section-index.html#index

-- Special cases, these items occur both as an HTML tag and an HTML attribute.
-- We keep those polymorph.

abbr, cite, command, data_, form, label, span, style, title :: IsString a => a

abbr = "abbr"
cite = "cite"
command = "command"
data_ = "data"
form = "form"
label = "label"
span = "span"
style = "style"
title = "title"

a, address, area, article, aside, audio, b, base, bdi, bdo, blockquote,
  body, br, button, canvas, caption, code, col, colgroup, datalist, dd, del,
  details, dfn, dialog, div, dl, dt, em, embed, fieldset, figcaption, figure,
  footer, h1, h2, h3, h4, h5, h6, head, header, hgroup, hr, html, i, iframe,
  img, input, ins, kbd, keygen, legend, li, link, map, mark, menu, meta, meter,
  nav, noscript, object, ol, optgroup, option, output, p, param, pre, progress,
  q, rp, rt, ruby, s, samp, script, section, select, small, source, strong,
  sub, summary, sup, table, tbody, td, textarea, tfoot, th, thead, time, tr,
  track, u, ul, var, video, wbr :: Selector

a = "a"
address = "address"
area = "area"
article = "article"
aside = "aside"
audio = "audio"
b = "b"
base = "base"
bdi = "bdi"
bdo = "bdo"
blockquote = "blockquote"
body = "body"
br = "br"
button = "button"
canvas = "canvas"
caption = "caption"
code = "code"
col = "col"
colgroup = "colgroup"
datalist = "datalist"
dd = "dd"
del = "del"
details = "details"
dfn = "dfn"
dialog = "dialog"
div = "div"
dl = "dl"
dt = "dt"
em = "em"
embed = "embed"
fieldset = "fieldset"
figcaption = "figcaption"
figure = "figure"
footer = "footer"
h1 = "h1"
h2 = "h2"
h3 = "h3"
h4 = "h4"
h5 = "h5"
h6 = "h6"
head = "head"
header = "header"
hgroup = "hgroup"
hr = "hr"
html = "html"
i = "i"
iframe = "iframe"
img = "img"
input = "input"
ins = "ins"
kbd = "kbd"
keygen = "keygen"
legend = "legend"
li = "li"
link = "link"
map = "map"
mark = "mark"
menu = "menu"
meta = "meta"
meter = "meter"
nav = "nav"
noscript = "noscript"
object = "object"
ol = "ol"
optgroup = "optgroup"
option = "option"
output = "output"
p = "p"
param = "param"
pre = "pre"
progress = "progress"
q = "q"
rp = "rp"
rt = "rt"
ruby = "ruby"
s = "s"
samp = "samp"
script = "script"
section = "section"
select = "select"
small = "small"
source = "source"
strong = "strong"
sub = "sub"
summary = "summary"
sup = "sup"
table = "table"
tbody = "tbody"
td = "td"
textarea = "textarea"
tfoot = "tfoot"
th = "th"
thead = "thead"
time = "time"
tr = "tr"
track = "track"
u = "u"
ul = "ul"
var = "var"
video = "video"
wbr = "wbr"

accept, acceptCharset, accesskey, action, alt, async, autocomplete, autofocus,
  autoplay, challenge, charset, checked, class_, cols, colspan, content,
  contenteditable, contextmenu, controls, coords, crossorigin, datetime,
  default_, defer, dir, dirname, disabled, download, draggable, dropzone,
  enctype, for, formaction, formenctype, formmethod, formnovalidate,
  formtarget, headers, height, hidden, high, href, hreflang, httpEquiv, icon,
  id, inert, inputmode, ismap, itemid, itemprop, itemref, itemscope, itemtype,
  keytype, kind, lang, list, loop, low, manifest, max, maxlength, media,
  mediagroup, method, min, multiple, muted, name, novalidate, open, optimum,
  pattern, ping, placeholder, poster, preload, radiogroup, readonly, rel,
  required, reversed, rows, rowspan, sandbox, scope, scoped, seamless,
  selected, shape, size, sizes, spellcheck, src, srcdoc, srclang, srcset,
  start, step, tabindex, target, translate, type_, typemustmatch, usemap,
  value, width, wrap :: Filter

accept = "accept"
acceptCharset = "accept-charset"
accesskey = "accesskey"
action = "action"
alt = "alt"
async = "async"
autocomplete = "autocomplete"
autofocus = "autofocus"
autoplay = "autoplay"
challenge = "challenge"
charset = "charset"
checked = "checked"
class_ = "class"
cols = "cols"
colspan = "colspan"
content = "content"
contenteditable = "contenteditable"
contextmenu = "contextmenu"
controls = "controls"
coords = "coords"
crossorigin = "crossorigin"
datetime = "datetime"
default_ = "default"
defer = "defer"
dir = "dir"
dirname = "dirname"
disabled = "disabled"
download = "download"
draggable = "draggable"
dropzone = "dropzone"
enctype = "enctype"
for = "for"
formaction = "formaction"
formenctype = "formenctype"
formmethod = "formmethod"
formnovalidate = "formnovalidate"
formtarget = "formtarget"
headers = "headers"
height = "height"
hidden = "hidden"
high = "high"
href = "href"
hreflang = "hreflang"
httpEquiv = "http-equiv"
icon = "icon"
id = "id"
inert = "inert"
inputmode = "inputmode"
ismap = "ismap"
itemid = "itemid"
itemprop = "itemprop"
itemref = "itemref"
itemscope = "itemscope"
itemtype = "itemtype"
keytype = "keytype"
kind = "kind"
lang = "lang"
list = "list"
loop = "loop"
low = "low"
manifest = "manifest"
max = "max"
maxlength = "maxlength"
media = "media"
mediagroup = "mediagroup"
method = "method"
min = "min"
multiple = "multiple"
muted = "muted"
name = "name"
novalidate = "novalidate"
open = "open"
optimum = "optimum"
pattern = "pattern"
ping = "ping"
placeholder = "placeholder"
poster = "poster"
preload = "preload"
radiogroup = "radiogroup"
readonly = "readonly"
rel = "rel"
required = "required"
reversed = "reversed"
rows = "rows"
rowspan = "rowspan"
sandbox = "sandbox"
scope = "scope"
scoped = "scoped"
seamless = "seamless"
selected = "selected"
shape = "shape"
size = "size"
sizes = "sizes"
spellcheck = "spellcheck"
src = "src"
srcdoc = "srcdoc"
srclang = "srclang"
srcset = "srcset"
start = "start"
step = "step"
tabindex = "tabindex"
target = "target"
translate = "translate"
type_ = "type"
typemustmatch = "typemustmatch"
usemap = "usemap"
value = "value"
width = "width"
wrap = "wrap"

